aws-samples/one-observability-demo

PetAdoptions/cdk/pet_stack/resources/destroy_stack.sh
=> Clean up on destroy script

PetAdoptions/envsetup.sh
=> Pull tracker file

PetAdoptions/cdk/pet_stack/package.json
=> Changes to fix ddb seeder issue

PetAdoptions/envsetup.sh
=> S3 pull region addition

PetAdoptions/cdk/pet_stack/package.json
=> Increment constructs to 3.0.4

PetAdoptions/petsite/petsite/bundleconfig.json
=> Edit bundlerconfig

PetAdoptions/petsite/petsite/PetSite.csproj
=> Change framework version to fix build issue

PetAdoptions/cdk/pet_stack/lib/services.ts, PetAdoptions/cdk/pet_stack/package.json, PetAdoptions/cdk/pet_stack/resources/cwagent-ecs-prometheus-metric-for-awsvpc.yaml, PetAdoptions/cdk/pet_stack/resources/destroy_stack.sh
=> Add files for ECS Prometheus metrics

PetAdoptions/cdk/pet_stack/lib/services.ts, PetAdoptions/cdk/pet_stack/lib/services/pet-site-service.ts, PetAdoptions/cdk/pet_stack/lib/services/stepfn.ts, PetAdoptions/cdk/pet_stack/package.json, PetAdoptions/cdk/pet_stack/resources/lambda_step_priceGreaterThan55.py, PetAdoptions/cdk/pet_stack/resources/lambda_step_priceLessThan55.py, PetAdoptions/cdk/pet_stack/resources/lambda_step_readDDB.py, PetAdoptions/petsite/.idea/.idea.petsite/.idea/contentModel.xml, PetAdoptions/petsite/petsite/Controllers/PaymentController.cs, PetAdoptions/petsite/petsite/PetSite.csproj
=> Step Function feature

PetAdoptions/cdk/pet_stack/resources/eksdeployment.sh, PetAdoptions/petsite/petsite/SystemsManagerConfigurationProviderWithReload.cs
=> Add StepFn

PetAdoptions/cdk/pet_stack/resources/fargate-resize-dashboard.json
=> Add Fargate resize dashboard json

PetAdoptions/petsearch/petsearch/Controllers/SearchController.cs
=> Reduce S3 create bucket hits

PetAdoptions/petsearch/petsearch/Controllers/SearchController.cs
=> change randomness

PetAdoptions/payforadoption-go/payforadoption/middlewares.go, PetAdoptions/payforadoption-go/payforadoption/repository.go, PetAdoptions/petlistadoptions-go/petlistadoptions/middlewares.go
- Unique annotation key names
- Add custom subsgements to match demo
=> Fix annotation keys

PetAdoptions/cdk/pet_stack/lib/services.ts
Fixed error with Trust Policy with X-Ray (missing dot)
=> Fixed error on X-Ray trust policy

PetAdoptions/cdk/pet_stack/lib/services/stepfn.ts
=> Added ADOT Lambda

PetAdoptions/cdk/pet_stack/lib/services/ecs-service.ts
=> Change log stream name param

PetAdoptions/cdk/pet_stack/cdk.json, PetAdoptions/cdk/pet_stack/lib/services.ts, PetAdoptions/cdk/pet_stack/lib/services/ecs-service.ts, PetAdoptions/cdk/pet_stack/lib/services/list-adoptions-service.ts, PetAdoptions/cdk/pet_stack/lib/services/pay-for-adoption-service.ts, PetAdoptions/cdk/pet_stack/lib/services/pet-site-service.ts, PetAdoptions/cdk/pet_stack/lib/services/search-service.ts, PetAdoptions/cdk/pet_stack/lib/services/traffic-generator-service.ts
=> Use public ECR registry

PetAdoptions/payforadoption-go/config.go, PetAdoptions/payforadoption-go/go.mod, PetAdoptions/payforadoption-go/go.sum, PetAdoptions/payforadoption-go/main.go, PetAdoptions/payforadoption-go/payforadoption/endpoint.go, PetAdoptions/payforadoption-go/payforadoption/repository.go, PetAdoptions/payforadoption-go/payforadoption/service.go, PetAdoptions/payforadoption-go/payforadoption/transport.go, PetAdoptions/payforadoption-go/seed.json
=> DDB seeding 

PetAdoptions/cdk/pet_stack/lib/services.ts, PetAdoptions/payforadoption-go/Dockerfile
=> Fix seeding API

PetAdoptions/payforadoption-go/payforadoption/service.go
Trigger seeding as part of cleanup API
=> Trigger seeding on housekeeping

PetAdoptions/petsite/petsite/Controllers/HomeController.cs
=> Adjust housekeeping logic

PetAdoptions/trafficgenerator/trafficgenerator/Worker.cs
=> Move-up housekeeping

PetAdoptions/trafficgenerator/trafficgenerator/Worker.cs
=> Wait for housekeeping

PetAdoptions/trafficgenerator/trafficgenerator/Worker.cs
=> Added comments

PetAdoptions/trafficgenerator/trafficgenerator/Worker.cs
=> Reset to 5

PetAdoptions/petsearch/petsearch/appsettings.json, PetAdoptions/petsite/petsite/appsettings.json
=> Edit plugins

PetAdoptions/petsite/petsite/PetSite.csproj
=> Update dependencies to support IRSA

PetAdoptions/cdk/pet_stack/resources/amp-eks-prometheus-daemonset.yaml, PetAdoptions/cdk/pet_stack/resources/amp-setup-irsa-eks.sh, PetAdoptions/cdk/pet_stack/resources/petadoptions-grafana-dashboard.json
=> Grafana dashboard and amp deployment scripts

PetAdoptions/cdk/pet_stack/lib/services.ts
- Added traffic Generator Service
- Removed conditional for EKS Cluster admin.  Cluster admin will be added if specified.
=> Added traffic Generator Service

PetAdoptions/cdk/pet_stack/lib/services.ts
Attempt to orchestrate the deployment of the ALB Controller and the application.
Added two resources (kubectl get) for the Service account and for the
load balancer webhook service.
To be tested on EE
=> Added KubernetesObjectValue resources

PetAdoptions/petsearch-java/build.gradle, PetAdoptions/petsearch-java/src/main/java/ca/petsearch/ApplicationFilter.java, PetAdoptions/petsearch-java/src/main/java/ca/petsearch/MetricEmitter.java, PetAdoptions/petsearch-java/src/main/java/ca/petsearch/WebConfig.java, PetAdoptions/petsearch-java/src/main/java/ca/petsearch/controllers/SearchController.java
*Issue #, if available:*  4
- Added spans according to the C# version
- Added new metrics as new examples
=> Add OpenTelemetry Spans and metrics

PetAdoptions/cdk/pet_stack/lib/applications.ts, PetAdoptions/cdk/pet_stack/resources/destroy_stack.sh
Added stack name for the Application stack to use in the cleanup script.
Added cleanup of the Application stack in the cleanup script
=> Fixed clean up script

PetAdoptions/cdk/pet_stack/lib/services.ts, PetAdoptions/cdk/pet_stack/lib/services/ecs-service.ts
=> Add desiredcount

PetAdoptions/cdk/pet_stack/lib/services.ts, PetAdoptions/cdk/pet_stack/lib/services/ecs-service.ts
=> Tighten up RDS access, limit TG count

PetAdoptions/cdk/pet_stack/lib/services.ts
=> Change repository URI to recognizable URI

PetAdoptions/cdk/pet_stack/resources/amp-setup-irsa-eks.sh, PetAdoptions/cdk/pet_stack/resources/amp_ingest_override_values.yaml, cloud9-cfn.yaml
=> Service Account fixes

PetAdoptions/cdk/pet_stack/resources/amp-setup-irsa-eks.sh, PetAdoptions/cdk/pet_stack/resources/amp_ingest_override_values.yaml, cloud9-cfn.yaml
=> Update dev from gl

PetAdoptions/cdk/pet_stack/resources/amp-eks-adot-prometheus-daemonset.yaml
=> ADOT changes

PetAdoptions/cdk/pet_stack/resources/amp_ingest_override_values.yaml
=> Remove the extra SigV4 property

PetAdoptions/cdk/pet_stack/resources/amp_ingest_override_values.yaml
=> Remove version override for prometheus image

PetAdoptions/cdk/pet_stack/resources/microservices/payforadoption-go, PetAdoptions/cdk/pet_stack/resources/microservices/petlistadoptions-go, PetAdoptions/cdk/pet_stack/resources/microservices/petsearch-java, PetAdoptions/cdk/pet_stack/resources/microservices/trafficgenerator
Fixing local builds when using cdk
=> Fix local builds when using cdk

PetAdoptions/cdk/pet_stack/buildspec.yml, PetAdoptions/cdk/pet_stack/resources/amp-setup-irsa-eks.sh
=> Remove zip dependency

PetAdoptions/cdk/pet_stack/resources/petadoptions-grafana-dashboard.json
=> Change datasource name

PetAdoptions/envsetup.sh
=> Remove tracker

PetAdoptions/petsearch-java/Dockerfile, PetAdoptions/petsearch-java/build.gradle, PetAdoptions/petsearch-java/src/main/java/ca/petsearch/MetricEmitter.java
=> OpenTelemetry version to 1.3.0 and use OpenTelemetry BOM

PetAdoptions/petsearch-java/build.gradle
This reverts commit 86d7b55ae2f72955b029ebc28fb82d2dc76f53e1, reversing
changes made to 82bc27c580b76e64728390d665b07df94e649243.
=> Revert "Merge pull request #154 from fbdo/log4j-cve-2021045046-fix"

PetAdoptions/cdk/pet_stack/lib/services/ecs-service.ts, PetAdoptions/cdk/pet_stack/resources/amp_ingest_kubecost_override_values.yaml, PetAdoptions/cdk/pet_stack/resources/extra_scrape_configs.yaml, PetAdoptions/petsearch-java/Dockerfile, PetAdoptions/petsearch-java/build.gradle, PetAdoptions/petsearch-java/docker-compose.yml, PetAdoptions/petsearch-java/gradle/wrapper/gradle-wrapper.properties, PetAdoptions/petsearch-java/src/main/java/ca/petsearch/MetricEmitter.java, PetAdoptions/petsearch-java/src/main/java/ca/petsearch/WebConfig.java, PetAdoptions/petsearch-java/src/main/java/ca/petsearch/controllers/SearchController.java, PetAdoptions/petsearch-java/src/main/resources/application.yml, PetAdoptions/petsearch-java/src/test/resources/application-test.yml, buildspec.yml
=> Petsearch changes

PetAdoptions/cdk/pet_stack/resources/amp_ingest_override_values.yaml
=> Prom serverconfig

PetAdoptions/cdk/pet_stack/lib/services/status-updater-service.ts, PetAdoptions/cdk/pet_stack/lib/services/stepfn.ts
=> Update Lambda Insights version

cloud9-cfn.yaml
=> Update bootstrap lambda to v3.9

PetAdoptions/cdk/pet_stack/lib/services/stepfn.ts
=> Update stepfn lambda v39

PetAdoptions/cdk/pet_stack/lib/services/stepfn.ts, cloud9-cfn.yaml
=> Lambda layer update

PetAdoptions/cdk/pet_stack/lib/services.ts, PetAdoptions/cdk/pet_stack/lib/services/stepfn.ts, PetAdoptions/cdk/pet_stack/resources/otel-collector-prometheus.yaml, PetAdoptions/payforadoption-go/Dockerfile, PetAdoptions/petlistadoptions-go/Dockerfile
=> Adot aigv4 pipeline

PetAdoptions/cdk/pet_stack/lib/services/status-updater-service.ts, PetAdoptions/petsearch-java/Dockerfile
=> Nodejs version upgrade

PetAdoptions/cdk/pet_stack/lib/services/status-updater-service.ts, PetAdoptions/cdk/pet_stack/resources/build-adot-ecr.sh
=> Update ecs build

PetAdoptions/cdk/pet_stack/lib/services.ts
=> Upgrade EKS to V23

gitops/git-repository.yaml, gitops/grafana-kustomization.yaml, grafana-dashboards/cluster.json, grafana-dashboards/kubelet.json, grafana-dashboards/namespace-workloads.json, grafana-dashboards/nodeexporter-nodes.json, grafana-dashboards/nodes.json, grafana-dashboards/workloads.json, grafana-operator-manifests/amg_grafana-amp-datasource.yaml, grafana-operator-manifests/amg_grafana-cw-datasource.yaml, grafana-operator-manifests/amg_grafana-dashboard.yaml, grafana-operator-manifests/amg_grafana-identity.yaml, grafana-operator-manifests/amg_grafana-xray-datasource.yaml, grafana-operator-manifests/kustomization.yaml
=> GitOps with Amazon Managed Grafana Workshop Module Snippets

PetAdoptions/payforadoption-go/Dockerfile, PetAdoptions/petlistadoptions-go/Dockerfile
=> Bump Go build container

PetAdoptions/cdk/pet_stack/lib/services.ts
Bump PG Aurora Serverless V1 to latest version
=> Bump aurora serverless v1

PetAdoptions/petsearch-java/manual-instrumentation-complete/src/main/java/ca/petsearch/Application.java, PetAdoptions/petsearch-java/manual-instrumentation-complete/src/main/java/ca/petsearch/ApplicationFilter.java, PetAdoptions/petsearch-java/manual-instrumentation-complete/src/main/java/ca/petsearch/MetricEmitter.java, PetAdoptions/petsearch-java/manual-instrumentation-complete/src/main/java/ca/petsearch/PseudoRandomNumberGenerator.java, PetAdoptions/petsearch-java/manual-instrumentation-complete/src/main/java/ca/petsearch/RandomNumberGenerator.java, PetAdoptions/petsearch-java/manual-instrumentation-complete/src/main/java/ca/petsearch/TracingLogFilter.java, PetAdoptions/petsearch-java/manual-instrumentation-complete/src/main/java/ca/petsearch/TracingRequestInterceptor.java, PetAdoptions/petsearch-java/manual-instrumentation-complete/src/main/java/ca/petsearch/WebConfig.java, PetAdoptions/petsearch-java/manual-instrumentation-complete/src/main/java/ca/petsearch/controllers/HealthController.java, PetAdoptions/petsearch-java/manual-instrumentation-complete/src/main/java/ca/petsearch/controllers/Pet.java, PetAdoptions/petsearch-java/manual-instrumentation-complete/src/main/java/ca/petsearch/controllers/SearchController.java, PetAdoptions/petsearch-java/manual-instrumentation-complete/src/main/resources/application.yml, PetAdoptions/petsearch-java/manual-instrumentation-complete/src/main/resources/logback-spring.xml, PetAdoptions/petsearch-java/manual-instrumentation-complete/src/test/java/ca/petsearch/PseudoRandomNumberGeneratorTest.java, PetAdoptions/petsearch-java/manual-instrumentation-complete/src/test/java/ca/petsearch/controllers/SearchControllerIT.java, PetAdoptions/petsearch-java/manual-instrumentation-complete/src/test/resources/application-test.yml
Manual instrumentation for Java
=> Manual instr

PetAdoptions/cdk/pet_stack/resources/cwagent-fluent-bit-quickstart.yaml, PetAdoptions/cdk/pet_stack/resources/prometheus-eks.yaml, PetAdoptions/petadoptionshistory-py/requirements.txt, PetAdoptions/petsite/petsite/Dockerfile, PetAdoptions/petsite/petsite/PetSite.csproj
* Fixes CWCI EKS issue. Updates to latest quick start instructions.
* Upgrades PetSite app to .NET 7.0
=> Fix CWCI EKS issue

PetAdoptions/petsite/petsite/Dockerfile, PetAdoptions/petsite/petsite/PetSite.csproj
=> Bump staging to main

PetAdoptions/petsite/petsite/Dockerfile, PetAdoptions/petsite/petsite/PetSite.csproj
=> Make it inline with staging

PetAdoptions/cdk/pet_stack/lib/services.ts, PetAdoptions/petsite/petsite/Dockerfile, PetAdoptions/petsite/petsite/PetSite.csproj
=> Addon version

PetAdoptions/cdk/pet_stack/package.json
=> Deps: upgrade dependencies

PetAdoptions/cdk/pet_stack/lib/common/container-image-builder.ts, buildspec.yml
=> Deps upgrade

PetAdoptions/cdk/pet_stack/lib/services.ts, cloud9-cfn.yaml
=> Build fixes

cloud9-cfn.yaml
N/A
Added reboot step for EC2 instance to ensure Cloud9 SSM-Agent connects with the control plane. This fixes the bootstrap issues presented recently.
=> Fix Cloud9 Bootstrap issues

PetAdoptions/cdk/pet_stack/resources/destroy_stack.sh, setup-cloudshell.sh
=> Cloudshell migration scripts

codepipeline-stack.yaml
Updating the codepipeline-stack.yml file with github user variable to allow testing from forked branches
=> Update codepipeline-stack.yml file with github user variable

PetAdoptions/cdk/pet_stack/lib/services.ts, PetAdoptions/cdk/pet_stack/package.json
Update PetSite application ECS clusters with enhanced observability and update dependencies to latest version to accommodate above changes
=> Update PetSite application ECS clusters with enhanced observability

PetAdoptions/cdk/pet_stack/lib/services.ts
=> adding dbinsights advanced for aurora cluster

PetAdoptions/petadoptionshistory-py/petadoptionshistory.py, PetAdoptions/petadoptionshistory-py/requirements.txt
- Update psycopg2 package to psycopg3
https://pypi.org/project/psycopg2/
- Update boto3 to latest version
=> Update psycopg2 package to psycopg3

PetAdoptions/cdk/pet_stack/lib/services/ecs-service.ts, PetAdoptions/cdk/pet_stack/resources/load_balancer/iam_policy.json, PetAdoptions/keycloak-setup.sh
N/A
Updated KeyCloack configuration script.
=> KeyCloak fixes

.github/workflows/acceptance-tests.yaml
=> Allow running tests on PRs to main

.github/workflows/acceptance-tests.yaml, PetAdoptions/cdk/pet_stack/lib/services.ts
=> Staging udpates

aws-codeguru-reviewer.yml
=> Disable code guru comments

.gitignore, PetAdoptions/payforadoption-go/benchmark/benchmark.yaml, PetAdoptions/payforadoption-go/config.go, PetAdoptions/payforadoption-go/example_request.sh, PetAdoptions/payforadoption-go/go.mod, PetAdoptions/payforadoption-go/payforadoption/benchmark_test.go, PetAdoptions/payforadoption-go/payforadoption/database.go, PetAdoptions/payforadoption-go/payforadoption/database_test.go, PetAdoptions/payforadoption-go/payforadoption/repository.go, PetAdoptions/payforadoption-go/payforadoption/service.go, PetAdoptions/payforadoption-go/payforadoption/service_test.go, PetAdoptions/payforadoption-go/payforadoption/utils.go
This PR refactors the error mode degradation system and cleans up the architecture by eliminating code duplication, improving dependency injection, and enabling realistic database connection exhaustion scenarios for AWS observability workshops.
Degradation Scenarios (Random Selection):
- Circuit Breaker - Simulated service failures with network timeouts
- System Stress  - Memory leaks + CPU pressure for resource monitoring
- Database Connection Exhaustion - Real PostgreSQL connection pool exhaustion
- Default Degradation  - Network latency simulation
New Realistic Database Testing:
- Real connection exhaustion: Opens 50+ actual database connections
- Automatic cleanup: Connections released after 45 seconds
- Observable failures: Triggers real PostgreSQL …
=> Enhance error mode

CONTRIBUTING.md, src/applications/microservices/petsearch-java/Dockerfile, src/applications/microservices/petsearch-java/src/main/resources/logback-spring.xml, src/cdk/bin/environment.ts, src/cdk/lib/constructs/dynamodb.ts, src/cdk/lib/constructs/ecs-service.ts, src/cdk/lib/constructs/microservice.ts, src/cdk/lib/constructs/serverless/functions/pipeline-retry/index.py, src/cdk/lib/microservices/petfood.ts, src/cdk/lib/microservices/petlist-adoptions.ts, src/cdk/lib/microservices/petsite.ts, src/cdk/lib/stages/applications.ts, src/cdk/lib/stages/containers.ts
NA
- Fix from cleanup task.
- Added petfood service and tables
=> Fix/buildfixes - Petfood

src/cdk/bin/constants.ts, src/cdk/lib/constructs/vpc-endpoints.ts
N/A
Added VPC Endpoints to avoid internet traffic where possible.
=> feat: added vpce

src/applications/microservices/petsite-net/petsite/Controllers/HomeController.cs, src/applications/microservices/petsite-net/petsite/Controllers/PaymentController.cs
- /debug-config endpoint error fix. Now returns a well formatted JSON.
=> Fix for debug-config endpoint

src/applications/microservices/payforadoption-go/payforadoption/endpoint.go, src/applications/microservices/payforadoption-go/payforadoption/middlewares.go, src/applications/microservices/payforadoption-go/payforadoption/repository.go, src/applications/microservices/payforadoption-go/payforadoption/service.go, src/applications/microservices/payforadoption-go/payforadoption/service_test.go, src/applications/microservices/payforadoption-go/payforadoption/transport.go
From `POST /api/cleanupadoptions` to `DELETE /api/cleanupadoptions/{userID}`
=> impr(payforadoptions): Delete transactions scoped to a user

src/applications/microservices/petsite-net/petsite/Controllers/AdoptionController.cs, src/cdk/lib/serverless/functions/status-updater/status-updater.ts
=> fix(app signals): pet node updater

src/applications/microservices/petlistadoptions-py/app.py, src/applications/microservices/petlistadoptions-py/requirements.txt, src/applications/microservices/petsearch-java/manual-instrumentation-complete/src/main/java/ca/petsearch/controllers/SearchController.java, src/applications/microservices/petsearch-java/src/main/java/ca/petsearch/controllers/HealthController.java, src/applications/microservices/petsearch-java/src/main/java/ca/petsearch/controllers/SearchController.java
=> More logs and traces
